version: '3.3'

services:
  client-admin:
    build: .
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    ports:
      - "4200:4200"
    # command: >
    #   bash -c "npm run serve:ssr"
    command: >
      bash -c "ng serve --host 0.0.0.0 --port 4200"
